### PR TITLE
Some Code cleanup to make it easier to read.

### PR DESCRIPTION
**Pull request by roboter5123**
In order to be able to maintain this project easier in your spare time it's important to write code cleanly. this saves you time by making bugs easier to find and removing technical debt.

Please check if the logic is still the same as you need.

### CODE REVIEW

**Comment by roboter5123** [comment]
Please give me your code formatter so i can run it over the code again in order to minimize formatting changes

**Comment by NewAmazingPVP** [comment]
@roboter5123 Thank you for the PR! I agree. I'll have to admit this is my worst organized public plugin just because of how it started and never really got time to organize it while taking in feature requests. So thank you so much for spending your time organizing this mess; it helps a lot having the organized code! I think your PR looks rock solid, so I am ready to merge it unless you have something else to add.

**Comment by NewAmazingPVP** [comment]
I use the built-in IntelliJ code formatter if that helps!

**Comment by roboter5123** [comment]
I think i am done

**Comment by roboter5123** [comment]
Actually i think i found some more things yesterday that i need to fix. So please give me some more time to fix the mistakes i made

**Comment by NewAmazingPVP** [comment]
@roboter5123 That's perfectly fine! Take your time, I'll also help here and there when I get time to!

**Comment by NewAmazingPVP** [comment]
@roboter5123 I just looked over the code, and it looks mostly identical. I think we can merge it for now, and if any bugs arise, we can always fix it later.

**Comment by NewAmazingPVP** [comment]
@roboter5123 Just tested, and it looks like it works for all my sample plugins, so I will go ahead and merge it. I apologize for the short notice, but I wanted to release the new version for all my plugins today, now that I have some spare time. Please feel free to work on this or a new PR after the merge if you want.

**Comment by roboter5123** [comment]
Sure thing. I am currently really busy again suddenly. If you need anything from me just hit me up and I'll see if i can do someting for you

**Pull request merged**
